# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-04 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appQRMusical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='timeout',
            field=models.IntegerField(default=5000),
        ),
        migrations.AlterField(
            model_name='settings',
            name='image_height',
            field=models.IntegerField(default=640),
        ),
        migrations.AlterField(
            model_name='settings',
            name='image_width',
            field=models.IntegerField(default=800),
        ),
    ]
