# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appQRMusical', '0002_auto_20170804_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=300)),
            ],
        ),
    ]
