# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 16:16
from __future__ import unicode_literals

import appQRMusical.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appQRMusical', '0004_auto_20170808_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='description',
        ),
        migrations.AddField(
            model_name='file',
            name='filename',
            field=models.CharField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=appQRMusical.models.directory_to_upload),
        ),
    ]
