# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appQRMusical', '0005_auto_20170809_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='filename',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
