# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appQRMusical', '0006_auto_20170809_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='filetype',
            field=models.CharField(blank=True, choices=[(b'mp3', b'Song'), (b'ogg', b'Sound'), (b'jpg', b'Image')], max_length=3),
        ),
    ]
