# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appQRMusical', '0007_file_filetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='filetype',
            field=models.CharField(blank=True, choices=[('mp3', 'Song'), ('ogg', 'Sound'), ('jpg', 'Image')], max_length=3),
        ),
    ]
