# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appQRMusical', '0009_auto_20170819_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='image_width',
            field=models.IntegerField(default=320),
        ),
    ]
